spring.application.name=application
spring.datasource.url=jdbc:postgresql://100.92.130.10/finance_db
spring.datasource.username=postgres
spring.datasource.password=1978Sveta@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkeymysupersecretkey

# Python service configuration
python.service.url=http://100.92.130.10